First
Lubow-k/Algorithms pull request #1
Opened 2023-02-09 13:13 UTC by Lubow-k

2023-02-10 14:29 UTC, Lubow-k commented on Task_1.py
> +
n - количество чисел в делимом, m - в делителе. Рассмотрим случай, когда n >= m (случай n < m не влияет на асимптотическую оценку). В худшем случае алгоритм пройдёт по (n-m+1) цифре* в делимом и будет подбирать для каждой число, вида  k * m, где k - это целая часть, которая будет записана в ответ. При этом 1 <= k <= 9.
Таким образом, (n-m+1) * (k*m)  = k*n*m - K*m*m + k*m = O(n*m) 
В наилучшем случае число К будет найдено для каждой цифры за 1 шаг, что даст оценку в n*m
В наихудшем случае будет произведен перебор от 1 до 10 для каждой цифры, т.е 10*n*m
*формально, он пройдёт по каждой цифре, но заходить в цикл while будет не всегда

2023-02-12 19:27 UTC, ugliansky commented on Task_1.py
> +
очень хорошо

2023-02-12 19:44 UTC, ugliansky requested changes

2023-02-12 19:44 UTC, ugliansky commented on Task_2_tests.py
> +                assert result == expected
вопрос: а откуда появились эти тестовые данные? в смысле ответы на них.

я к чему: вы ведь в Python, где из коробки работает длинная арифметика. Давайте обойдемся вообще без .out файлов, будем полагаться на то, что в длинной арифметике Python ошибок нет.

2023-02-12 19:44 UTC, ugliansky commented on Task_2.py
> +def Karatsuba(x, y, n):
это, конечно, фамилия, но еще это функция в данном случае, давайте с маленькой буквы)

2023-02-12 19:44 UTC, ugliansky commented on Task_2.py
> +def Karatsuba(x, y, n):
ну и давайте заверточку сделаем: функцию, которая принимает просто два числа, а возвращает их произведение (а внутри она вычисляет длину там, вызывает вот эту и т.д.). Для красоты

2023-02-12 19:44 UTC, ugliansky commented on Task_3.c
> +            return middle;
давайте начнем с позитивного варианта, что мы нашли элемент? а уж дальше все остальные проверки. Это, конечно, крохоборство, но все-таки

2023-02-12 19:44 UTC, ugliansky commented on Task_4.sh
> +    find a.out &>/dev/null
а нельзя здесь просто по `result`? наверное, если сработала компиляция, стоит ожидать, что `a.out` есть. А с другой стороны, если компиляция прошла, а a.out не породился, то, наверное, странно считать, что все ок.

Логичнее было бы: скомпилировали -> если ошибок нет, то вот тогда делаем find (он перетирает result) -> если и у него ошибок нет, то тогда запускаем a.out и уже он перетирает result.

2023-02-14 16:04 UTC, merged